name: Go with Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: npm install -g pm2
    - run: go test -cover github.com/yourtion/go-utils/nodejs
